import React, { useState, useEffect, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  ArrowLeft, Play, FileText, Brain, Search, Download,
  Mail, FileSpreadsheet, Headphones, Shield, Clock,
  ChevronDown, ChevronUp, ExternalLink, AlertTriangle,
  Check, Loader2, Building, Users, TrendingUp, Target,
  Briefcase, Globe, AlertCircle, Lightbulb
} from 'lucide-react'
import { api } from '../utils/api'
import { useMeetings } from '../contexts/MeetingsContext'

const TABS = {
  OVERVIEW: 'overview',
  TRANSCRIPT: 'transcript',
  ANALYSIS: 'analysis',
  RFP: 'rfp',
  RESEARCH: 'research',
  EXPORTS: 'exports'
}

export default function MeetingDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { getMeeting, apiStatus } = useMeetings()

  const [meeting, setMeeting] = useState(null)
  const [loading, setLoading] = useState(true)
  const [activeTab, setActiveTab] = useState(TABS.OVERVIEW)
  const [processing, setProcessing] = useState({
    transcription: false,
    analysis: false,
    research: false,
    powerpoint: false,
    podcast: false
  })
  const [error, setError] = useState(null)
  const [expandedSections, setExpandedSections] = useState({})

  // Fetch meeting data
  const fetchMeeting = useCallback(async () => {
    try {
      setLoading(true)
      const data = await getMeeting(id)
      setMeeting(data)

      // Auto-select RFP tab for RFP meetings
      if (data.meetingType === 'Fact-Finding Session (RFP)' && data.analysis) {
        setActiveTab(TABS.RFP)
      } else if (data.analysis) {
        setActiveTab(TABS.ANALYSIS)
      }
    } catch (err) {
      setError('Failed to load meeting')
      console.error(err)
    } finally {
      setLoading(false)
    }
  }, [id, getMeeting])

  useEffect(() => {
    fetchMeeting()
  }, [fetchMeeting])

  // Transcribe meeting
  const handleTranscribe = async () => {
    try {
      setProcessing(prev => ({ ...prev, transcription: true }))
      setError(null)
      await api.transcribeMeeting(id)
      await fetchMeeting()
    } catch (err) {
      setError('Transcription failed: ' + err.message)
    } finally {
      setProcessing(prev => ({ ...prev, transcription: false }))
    }
  }

  // Analyze meeting
  const handleAnalyze = async () => {
    try {
      setProcessing(prev => ({ ...prev, analysis: true }))
      setError(null)
      await api.analyzeMeeting(id)
      await fetchMeeting()
    } catch (err) {
      setError('Analysis failed: ' + err.message)
    } finally {
      setProcessing(prev => ({ ...prev, analysis: false }))
    }
  }

  // Deep Research
  const handleDeepResearch = async () => {
    try {
      setProcessing(prev => ({ ...prev, research: true }))
      setError(null)
      await api.runDeepResearch(id)
      await fetchMeeting()
      setActiveTab(TABS.RESEARCH)
    } catch (err) {
      setError('Deep Research failed: ' + err.message)
    } finally {
      setProcessing(prev => ({ ...prev, research: false }))
    }
  }

  // Generate PowerPoint
  const handleGeneratePowerPoint = async (type) => {
    try {
      setProcessing(prev => ({ ...prev, powerpoint: true }))
      setError(null)
      const result = await api.generatePowerPoint(id, type)
      if (result.downloadUrl) {
        window.open(result.downloadUrl, '_blank')
      }
    } catch (err) {
      setError('PowerPoint generation failed: ' + err.message)
    } finally {
      setProcessing(prev => ({ ...prev, powerpoint: false }))
    }
  }

  // Generate Podcast
  const handleGeneratePodcast = async (voiceType) => {
    try {
      setProcessing(prev => ({ ...prev, podcast: true }))
      setError(null)
      const result = await api.generatePodcast(id, voiceType)
      await fetchMeeting()
    } catch (err) {
      setError('Podcast generation failed: ' + err.message)
    } finally {
      setProcessing(prev => ({ ...prev, podcast: false }))
    }
  }

  // Email summary
  const handleEmailSummary = () => {
    if (!meeting?.analysis) return

    const subject = encodeURIComponent(`Meeting Summary: ${meeting.title}`)
    const body = encodeURIComponent(`
Meeting Summary: ${meeting.title}
Date: ${new Date(meeting.createdAt).toLocaleDateString()}
Type: ${meeting.meetingType}
${meeting.clientName ? `Client: ${meeting.clientName}` : ''}

SUMMARY:
${meeting.analysis.summary || 'No summary available'}

ACTION ITEMS:
${meeting.analysis.actionItems?.map(item =>
  `- ${item.task} (Owner: ${item.owner || 'TBD'}, Due: ${item.deadline || 'TBD'})`
).join('\n') || 'None'}

---
Generated by Marsh Meeting Analyzer
    `)

    window.location.href = `mailto:?subject=${subject}&body=${body}`
  }

  // Toggle section expansion
  const toggleSection = (section) => {
    setExpandedSections(prev => ({ ...prev, [section]: !prev[section] }))
  }

  // Format helpers
  const formatDate = (dateStr) => new Date(dateStr).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
  })

  const formatDuration = (seconds) => {
    if (!seconds) return '—'
    const mins = Math.floor(seconds / 60)
    const secs = Math.floor(seconds % 60)
    return `${mins}:${secs.toString().padStart(2, '0')}`
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <Loader2 className="w-8 h-8 animate-spin text-marsh-blue" />
      </div>
    )
  }

  if (!meeting) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="text-center py-12">
          <AlertTriangle className="w-12 h-12 text-red-500 mx-auto mb-4" />
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Meeting Not Found</h2>
          <button onClick={() => navigate('/')} className="text-marsh-blue hover:underline">
            Return to Dashboard
          </button>
        </div>
      </div>
    )
  }

  const isRFP = meeting.meetingType === 'Fact-Finding Session (RFP)'
  const hasTranscript = !!meeting.transcript
  const hasAnalysis = !!meeting.analysis
  const hasResearch = !!meeting.deepResearch

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Header */}
      <div className="mb-6">
        <button
          onClick={() => navigate('/')}
          className="flex items-center gap-2 text-gray-500 hover:text-gray-700 mb-4"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Dashboard
        </button>

        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <h1 className="text-2xl font-bold text-gray-900">{meeting.title}</h1>
              {isRFP && (
                <span className="px-3 py-1 bg-purple-100 text-purple-700 text-sm font-medium rounded-full flex items-center gap-1">
                  <FileSpreadsheet className="w-4 h-4" />
                  RFP Session
                </span>
              )}
              <span className={`px-2 py-1 text-xs font-medium rounded-full ${
                meeting.confidentiality === 'Confidential' ? 'bg-orange-100 text-orange-700' :
                meeting.confidentiality === 'Highly Confidential' ? 'bg-red-100 text-red-700' :
                'bg-blue-100 text-blue-700'
              }`}>
                <Shield className="w-3 h-3 inline mr-1" />
                {meeting.confidentiality}
              </span>
            </div>
            <div className="flex items-center gap-4 text-sm text-gray-500">
              <span className="flex items-center gap-1">
                <Clock className="w-4 h-4" />
                {formatDate(meeting.createdAt)}
              </span>
              <span>{formatDuration(meeting.duration)}</span>
              {meeting.clientName && (
                <span className="flex items-center gap-1">
                  <Building className="w-4 h-4" />
                  {meeting.clientName}
                </span>
              )}
            </div>
          </div>

          {/* Quick Actions */}
          <div className="flex items-center gap-2">
            {hasAnalysis && (
              <button
                onClick={handleEmailSummary}
                className="px-3 py-2 border border-gray-200 rounded-lg text-gray-700 hover:bg-gray-50 flex items-center gap-2 text-sm"
              >
                <Mail className="w-4 h-4" />
                Email Summary
              </button>
            )}
            {hasAnalysis && isRFP && !hasResearch && (
              <button
                onClick={handleDeepResearch}
                disabled={processing.research}
                className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 flex items-center gap-2 text-sm disabled:opacity-50"
              >
                {processing.research ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Search className="w-4 h-4" />
                )}
                Deep Research
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Error Alert */}
      {error && (
        <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg flex items-center gap-3 text-red-700">
          <AlertTriangle className="w-5 h-5" />
          <span>{error}</span>
          <button onClick={() => setError(null)} className="ml-auto text-red-500 hover:text-red-700">×</button>
        </div>
      )}

      {/* Processing Pipeline */}
      {!hasAnalysis && (
        <div className="bg-white rounded-xl border border-gray-200 p-6 mb-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Processing Pipeline</h2>
          <div className="flex items-center gap-4">
            {/* Step 1: Transcribe */}
            <div className={`flex-1 p-4 rounded-lg border-2 ${
              hasTranscript ? 'border-green-500 bg-green-50' :
              processing.transcription ? 'border-yellow-500 bg-yellow-50' :
              'border-gray-200'
            }`}>
              <div className="flex items-center gap-3">
                {hasTranscript ? (
                  <Check className="w-6 h-6 text-green-600" />
                ) : processing.transcription ? (
                  <Loader2 className="w-6 h-6 text-yellow-600 animate-spin" />
                ) : (
                  <FileText className="w-6 h-6 text-gray-400" />
                )}
                <div>
                  <h3 className="font-medium">1. Transcribe</h3>
                  <p className="text-sm text-gray-500">Convert audio to text</p>
                </div>
              </div>
              {!hasTranscript && !processing.transcription && (
                <button
                  onClick={handleTranscribe}
                  disabled={!apiStatus.openai}
                  className="mt-3 w-full px-4 py-2 bg-marsh-blue text-white rounded-lg hover:bg-marsh-dark-blue disabled:opacity-50"
                >
                  Start Transcription
                </button>
              )}
            </div>

            <ChevronDown className="w-6 h-6 text-gray-300 rotate-[-90deg]" />

            {/* Step 2: Analyze */}
            <div className={`flex-1 p-4 rounded-lg border-2 ${
              hasAnalysis ? 'border-green-500 bg-green-50' :
              processing.analysis ? 'border-yellow-500 bg-yellow-50' :
              hasTranscript ? 'border-gray-200' : 'border-gray-100 bg-gray-50 opacity-50'
            }`}>
              <div className="flex items-center gap-3">
                {hasAnalysis ? (
                  <Check className="w-6 h-6 text-green-600" />
                ) : processing.analysis ? (
                  <Loader2 className="w-6 h-6 text-yellow-600 animate-spin" />
                ) : (
                  <Brain className="w-6 h-6 text-gray-400" />
                )}
                <div>
                  <h3 className="font-medium">2. Analyze</h3>
                  <p className="text-sm text-gray-500">AI-powered insights</p>
                </div>
              </div>
              {hasTranscript && !hasAnalysis && !processing.analysis && (
                <button
                  onClick={handleAnalyze}
                  disabled={!apiStatus.anthropic}
                  className="mt-3 w-full px-4 py-2 bg-marsh-blue text-white rounded-lg hover:bg-marsh-dark-blue disabled:opacity-50"
                >
                  Start Analysis
                </button>
              )}
            </div>

            {isRFP && (
              <>
                <ChevronDown className="w-6 h-6 text-gray-300 rotate-[-90deg]" />

                {/* Step 3: Deep Research (RFP only) */}
                <div className={`flex-1 p-4 rounded-lg border-2 ${
                  hasResearch ? 'border-green-500 bg-green-50' :
                  processing.research ? 'border-purple-500 bg-purple-50' :
                  hasAnalysis ? 'border-gray-200' : 'border-gray-100 bg-gray-50 opacity-50'
                }`}>
                  <div className="flex items-center gap-3">
                    {hasResearch ? (
                      <Check className="w-6 h-6 text-green-600" />
                    ) : processing.research ? (
                      <Loader2 className="w-6 h-6 text-purple-600 animate-spin" />
                    ) : (
                      <Search className="w-6 h-6 text-gray-400" />
                    )}
                    <div>
                      <h3 className="font-medium">3. Deep Research</h3>
                      <p className="text-sm text-gray-500">Market intelligence</p>
                    </div>
                  </div>
                  {hasAnalysis && !hasResearch && !processing.research && (
                    <button
                      onClick={handleDeepResearch}
                      className="mt-3 w-full px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700"
                    >
                      Run Deep Research
                    </button>
                  )}
                </div>
              </>
            )}
          </div>
        </div>
      )}

      {/* Tabs */}
      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        <div className="border-b border-gray-200">
          <nav className="flex -mb-px">
            {[
              { id: TABS.OVERVIEW, label: 'Overview', icon: FileText },
              { id: TABS.TRANSCRIPT, label: 'Transcript', icon: FileText, disabled: !hasTranscript },
              { id: TABS.ANALYSIS, label: 'Analysis', icon: Brain, disabled: !hasAnalysis },
              ...(isRFP ? [{ id: TABS.RFP, label: 'RFP Builder', icon: FileSpreadsheet, disabled: !hasAnalysis }] : []),
              { id: TABS.RESEARCH, label: 'Deep Research', icon: Search, disabled: !hasResearch },
              { id: TABS.EXPORTS, label: 'Exports', icon: Download, disabled: !hasAnalysis }
            ].map(tab => (
              <button
                key={tab.id}
                onClick={() => !tab.disabled && setActiveTab(tab.id)}
                disabled={tab.disabled}
                className={`flex items-center gap-2 px-6 py-4 text-sm font-medium border-b-2 transition-colors ${
                  activeTab === tab.id
                    ? 'border-marsh-blue text-marsh-blue'
                    : tab.disabled
                    ? 'border-transparent text-gray-300 cursor-not-allowed'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
              >
                <tab.icon className="w-4 h-4" />
                {tab.label}
              </button>
            ))}
          </nav>
        </div>

        <div className="p-6">
          {/* Overview Tab */}
          {activeTab === TABS.OVERVIEW && (
            <OverviewTab meeting={meeting} />
          )}

          {/* Transcript Tab */}
          {activeTab === TABS.TRANSCRIPT && hasTranscript && (
            <TranscriptTab transcript={meeting.transcript} />
          )}

          {/* Analysis Tab */}
          {activeTab === TABS.ANALYSIS && hasAnalysis && (
            <AnalysisTab
              analysis={meeting.analysis}
              expandedSections={expandedSections}
              toggleSection={toggleSection}
            />
          )}

          {/* RFP Tab */}
          {activeTab === TABS.RFP && isRFP && hasAnalysis && (
            <RfpTab
              meeting={meeting}
              expandedSections={expandedSections}
              toggleSection={toggleSection}
              onDeepResearch={handleDeepResearch}
              processing={processing}
            />
          )}

          {/* Research Tab */}
          {activeTab === TABS.RESEARCH && hasResearch && (
            <ResearchTab
              research={meeting.deepResearch}
              expandedSections={expandedSections}
              toggleSection={toggleSection}
            />
          )}

          {/* Exports Tab */}
          {activeTab === TABS.EXPORTS && hasAnalysis && (
            <ExportsTab
              meeting={meeting}
              onGeneratePowerPoint={handleGeneratePowerPoint}
              onGeneratePodcast={handleGeneratePodcast}
              processing={processing}
              apiStatus={apiStatus}
            />
          )}
        </div>
      </div>
    </div>
  )
}

// Overview Tab Component
function OverviewTab({ meeting }) {
  return (
    <div className="space-y-6">
      {/* Audio Player */}
      <div>
        <h3 className="text-sm font-medium text-gray-700 mb-2">Recording</h3>
        <audio src={meeting.audioPath} controls className="w-full" />
      </div>

      {/* Meeting Info */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-gray-50 rounded-lg p-4">
          <p className="text-sm text-gray-500">Type</p>
          <p className="font-medium">{meeting.meetingType}</p>
        </div>
        <div className="bg-gray-50 rounded-lg p-4">
          <p className="text-sm text-gray-500">Status</p>
          <p className="font-medium capitalize">{meeting.status}</p>
        </div>
        <div className="bg-gray-50 rounded-lg p-4">
          <p className="text-sm text-gray-500">Confidentiality</p>
          <p className="font-medium">{meeting.confidentiality}</p>
        </div>
        <div className="bg-gray-50 rounded-lg p-4">
          <p className="text-sm text-gray-500">Duration</p>
          <p className="font-medium">{meeting.duration ? `${Math.floor(meeting.duration / 60)}:${Math.floor(meeting.duration % 60).toString().padStart(2, '0')}` : '—'}</p>
        </div>
      </div>

      {/* Summary Preview */}
      {meeting.analysis?.summary && (
        <div>
          <h3 className="text-sm font-medium text-gray-700 mb-2">Summary</h3>
          <p className="text-gray-600 bg-gray-50 rounded-lg p-4">{meeting.analysis.summary}</p>
        </div>
      )}
    </div>
  )
}

// Transcript Tab Component
function TranscriptTab({ transcript }) {
  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h3 className="font-medium text-gray-900">Full Transcript</h3>
        <span className="text-sm text-gray-500">
          Duration: {Math.floor(transcript.duration / 60)}:{Math.floor(transcript.duration % 60).toString().padStart(2, '0')}
        </span>
      </div>

      {transcript.segments?.length > 0 ? (
        <div className="space-y-3 max-h-[600px] overflow-y-auto">
          {transcript.segments.map((segment, idx) => (
            <div key={idx} className="flex gap-3">
              <span className="text-xs text-gray-400 font-mono w-12 flex-shrink-0 pt-1">
                {segment.timestamp}
              </span>
              <p className="text-gray-700">{segment.text}</p>
            </div>
          ))}
        </div>
      ) : (
        <div className="bg-gray-50 rounded-lg p-4 whitespace-pre-wrap text-gray-700">
          {transcript.text}
        </div>
      )}
    </div>
  )
}

// Analysis Tab Component
function AnalysisTab({ analysis, expandedSections, toggleSection }) {
  return (
    <div className="space-y-6">
      {/* Summary */}
      <div className="bg-marsh-blue/5 rounded-lg p-6">
        <h3 className="font-semibold text-marsh-blue mb-3">Executive Summary</h3>
        <p className="text-gray-700 leading-relaxed">{analysis.summary}</p>
      </div>

      {/* Key Topics */}
      {analysis.keyTopics?.length > 0 && (
        <CollapsibleSection
          title="Key Topics"
          icon={Target}
          count={analysis.keyTopics.length}
          expanded={expandedSections.keyTopics}
          onToggle={() => toggleSection('keyTopics')}
        >
          <div className="space-y-3">
            {analysis.keyTopics.map((topic, idx) => (
              <div key={idx} className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg">
                <span className={`px-2 py-0.5 text-xs font-medium rounded ${
                  topic.importance === 'high' ? 'bg-red-100 text-red-700' :
                  topic.importance === 'medium' ? 'bg-yellow-100 text-yellow-700' :
                  'bg-green-100 text-green-700'
                }`}>{topic.importance}</span>
                <div>
                  <h4 className="font-medium text-gray-900">{topic.topic}</h4>
                  <p className="text-sm text-gray-600">{topic.description}</p>
                </div>
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Action Items */}
      {analysis.actionItems?.length > 0 && (
        <CollapsibleSection
          title="Action Items"
          icon={Check}
          count={analysis.actionItems.length}
          expanded={expandedSections.actionItems !== false}
          onToggle={() => toggleSection('actionItems')}
        >
          <div className="space-y-3">
            {analysis.actionItems.map((item, idx) => (
              <div key={idx} className="p-4 border border-gray-200 rounded-lg">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <p className="font-medium text-gray-900">{item.task}</p>
                    {item.notes && <p className="text-sm text-gray-500 mt-1">{item.notes}</p>}
                  </div>
                  <span className={`px-2 py-0.5 text-xs font-medium rounded ${
                    item.priority === 'high' ? 'bg-red-100 text-red-700' :
                    item.priority === 'medium' ? 'bg-yellow-100 text-yellow-700' :
                    'bg-gray-100 text-gray-700'
                  }`}>{item.priority}</span>
                </div>
                <div className="flex items-center gap-4 mt-3 text-sm text-gray-500">
                  <span className="flex items-center gap-1">
                    <Users className="w-3 h-3" />
                    {item.owner || 'TBD'}
                  </span>
                  <span className="flex items-center gap-1">
                    <Clock className="w-3 h-3" />
                    {item.deadline || 'TBD'}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Business Implications */}
      {analysis.businessImplications?.length > 0 && (
        <CollapsibleSection
          title="Business Implications"
          icon={TrendingUp}
          count={analysis.businessImplications.length}
          expanded={expandedSections.implications}
          onToggle={() => toggleSection('implications')}
        >
          <div className="space-y-3">
            {analysis.businessImplications.map((item, idx) => (
              <div key={idx} className="p-4 bg-blue-50 rounded-lg border border-blue-100">
                <h4 className="font-medium text-blue-900">{item.implication}</h4>
                <p className="text-sm text-blue-700 mt-1">{item.impact}</p>
                {item.recommendation && (
                  <p className="text-sm text-blue-600 mt-2 flex items-center gap-1">
                    <Lightbulb className="w-3 h-3" />
                    {item.recommendation}
                  </p>
                )}
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Risk Exposures */}
      {analysis.riskExposures?.length > 0 && (
        <CollapsibleSection
          title="Risk Exposures Identified"
          icon={AlertCircle}
          count={analysis.riskExposures.length}
          expanded={expandedSections.risks}
          onToggle={() => toggleSection('risks')}
        >
          <div className="space-y-3">
            {analysis.riskExposures.map((risk, idx) => (
              <div key={idx} className="flex items-start gap-3 p-3 bg-gray-50 rounded-lg">
                <span className={`px-2 py-0.5 text-xs font-medium rounded ${
                  risk.severity === 'high' ? 'bg-red-100 text-red-700' :
                  risk.severity === 'medium' ? 'bg-yellow-100 text-yellow-700' :
                  'bg-green-100 text-green-700'
                }`}>{risk.severity}</span>
                <div>
                  <h4 className="font-medium text-gray-900">{risk.exposure}</h4>
                  {risk.coverageType && (
                    <p className="text-sm text-gray-500">Coverage: {risk.coverageType}</p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}
    </div>
  )
}

// RFP Tab Component
function RfpTab({ meeting, expandedSections, toggleSection, onDeepResearch, processing }) {
  const rfpData = meeting.rfpData
  const factFinding = rfpData?.factFindingSummary || {}
  const rfpDraft = rfpData?.rfpDraft || {}

  return (
    <div className="space-y-6">
      {/* Deep Research CTA */}
      {!meeting.deepResearch && (
        <div className="bg-purple-50 border border-purple-200 rounded-xl p-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-lg font-semibold text-purple-900">Ready for Deep Research?</h3>
              <p className="text-purple-700 mt-1">
                Run comprehensive market research including carrier appetite, regional risks, and competitive intelligence.
              </p>
            </div>
            <button
              onClick={onDeepResearch}
              disabled={processing.research}
              className="px-6 py-3 bg-purple-600 text-white rounded-lg hover:bg-purple-700 flex items-center gap-2 font-medium disabled:opacity-50"
            >
              {processing.research ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                <Search className="w-5 h-5" />
              )}
              Run Deep Research
            </button>
          </div>
        </div>
      )}

      {/* Client Profile */}
      <div className="bg-white border border-gray-200 rounded-xl overflow-hidden">
        <div className="bg-gray-50 px-6 py-4 border-b border-gray-200">
          <h3 className="font-semibold text-gray-900 flex items-center gap-2">
            <Building className="w-5 h-5" />
            Client Profile
          </h3>
        </div>
        <div className="p-6">
          <div className="grid grid-cols-2 md:grid-cols-3 gap-6">
            <div>
              <p className="text-sm text-gray-500">Client Name</p>
              <p className="font-medium">{factFinding.clientName || meeting.clientName || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Industry</p>
              <p className="font-medium">{factFinding.industry || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Location</p>
              <p className="font-medium">{factFinding.location || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Employees</p>
              <p className="font-medium">{factFinding.employeeCount || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Current Broker</p>
              <p className="font-medium">{factFinding.currentProgram?.incumbent || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500">Renewal Date</p>
              <p className="font-medium">{factFinding.currentProgram?.expirationDate || 'N/A'}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Pain Points */}
      {factFinding.painPoints?.length > 0 && (
        <CollapsibleSection
          title="Pain Points Identified"
          icon={AlertTriangle}
          count={factFinding.painPoints.length}
          expanded={expandedSections.painPoints !== false}
          onToggle={() => toggleSection('painPoints')}
        >
          <div className="space-y-3">
            {factFinding.painPoints.map((point, idx) => (
              <div key={idx} className="p-4 bg-orange-50 border border-orange-100 rounded-lg">
                <div className="flex items-start gap-3">
                  <span className={`px-2 py-0.5 text-xs font-medium rounded ${
                    point.severity === 'high' ? 'bg-red-100 text-red-700' :
                    point.severity === 'medium' ? 'bg-yellow-100 text-yellow-700' :
                    'bg-green-100 text-green-700'
                  }`}>{point.severity}</span>
                  <div>
                    <h4 className="font-medium text-gray-900">{point.issue}</h4>
                    {point.impact && <p className="text-sm text-gray-600 mt-1">{point.impact}</p>}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Coverage Recommendations */}
      {rfpDraft.recommendedCoverage?.length > 0 && (
        <CollapsibleSection
          title="Recommended Coverage Lines"
          icon={Shield}
          count={rfpDraft.recommendedCoverage.length}
          expanded={expandedSections.coverage !== false}
          onToggle={() => toggleSection('coverage')}
        >
          <div className="space-y-4">
            {rfpDraft.recommendedCoverage.map((coverage, idx) => (
              <div key={idx} className="p-4 border border-gray-200 rounded-lg">
                <h4 className="font-semibold text-marsh-blue">{coverage.line}</h4>
                <p className="text-sm text-gray-600 mt-2">{coverage.rationale}</p>
                {coverage.considerations && (
                  <p className="text-sm text-gray-500 mt-2 italic">{coverage.considerations}</p>
                )}
                {coverage.marketingApproach && (
                  <p className="text-sm text-marsh-light-blue mt-2">
                    <strong>Approach:</strong> {coverage.marketingApproach}
                  </p>
                )}
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Cross-Sell Opportunities */}
      {meeting.crossSellOpportunities?.length > 0 && (
        <div className="bg-gradient-to-r from-marsh-blue to-marsh-light-blue rounded-xl p-6 text-white">
          <h3 className="font-semibold text-lg mb-4 flex items-center gap-2">
            <Briefcase className="w-5 h-5" />
            Marsh McLennan Cross-Sell Opportunities
          </h3>
          <div className="grid md:grid-cols-3 gap-4">
            {meeting.crossSellOpportunities.map((opp, idx) => (
              <div key={idx} className="bg-white/10 rounded-lg p-4">
                <h4 className="font-semibold">{opp.company}</h4>
                <p className="text-sm opacity-80">{opp.focus}</p>
                {opp.opportunities?.[0] && (
                  <p className="text-sm mt-2">{opp.opportunities[0].rationale || opp.opportunities[0].service}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* RFP Draft Executive Summary */}
      {rfpDraft.executiveSummary && (
        <div className="bg-gray-50 rounded-xl p-6">
          <h3 className="font-semibold text-gray-900 mb-3">Draft Executive Summary</h3>
          <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">{rfpDraft.executiveSummary}</p>
        </div>
      )}

      {/* Marsh Value Proposition */}
      {rfpDraft.marshValueProposition && (
        <CollapsibleSection
          title="Marsh Value Proposition"
          icon={Globe}
          expanded={expandedSections.valueProp}
          onToggle={() => toggleSection('valueProp')}
        >
          <div className="grid md:grid-cols-2 gap-4">
            {Object.entries(rfpDraft.marshValueProposition).map(([key, value]) => (
              value && (
                <div key={key} className="p-4 bg-marsh-blue/5 rounded-lg">
                  <h4 className="font-medium text-marsh-blue capitalize">{key.replace(/([A-Z])/g, ' $1')}</h4>
                  <p className="text-sm text-gray-600 mt-1">{value}</p>
                </div>
              )
            ))}
          </div>
        </CollapsibleSection>
      )}
    </div>
  )
}

// Research Tab Component
function ResearchTab({ research, expandedSections, toggleSection }) {
  const brief = research.executiveBrief || {}

  return (
    <div className="space-y-6">
      {/* Executive Brief */}
      <div className="bg-purple-50 border border-purple-200 rounded-xl p-6">
        <h3 className="font-semibold text-purple-900 mb-4">Executive Research Brief</h3>

        {brief.keyFindings?.length > 0 && (
          <div className="mb-4">
            <h4 className="font-medium text-purple-800 mb-2">Key Findings</h4>
            <ul className="list-disc list-inside space-y-1">
              {brief.keyFindings.map((finding, idx) => (
                <li key={idx} className="text-purple-700">{finding}</li>
              ))}
            </ul>
          </div>
        )}

        {brief.criticalRisks?.length > 0 && (
          <div className="mb-4">
            <h4 className="font-medium text-purple-800 mb-2">Critical Risks</h4>
            <ul className="list-disc list-inside space-y-1">
              {brief.criticalRisks.map((risk, idx) => (
                <li key={idx} className="text-purple-700">{risk}</li>
              ))}
            </ul>
          </div>
        )}

        {brief.competitivePosition && (
          <div>
            <h4 className="font-medium text-purple-800 mb-2">Competitive Position</h4>
            <p className="text-purple-700">{brief.competitivePosition}</p>
          </div>
        )}
      </div>

      {/* Market Intelligence */}
      {research.marketIntelligence && (
        <CollapsibleSection
          title="Market Intelligence"
          icon={TrendingUp}
          expanded={expandedSections.market}
          onToggle={() => toggleSection('market')}
        >
          <div className="space-y-4">
            {research.marketIntelligence.carrierAppetite?.map((carrier, idx) => (
              <div key={idx} className="p-4 border border-gray-200 rounded-lg">
                <div className="flex items-center justify-between mb-2">
                  <h4 className="font-medium">{carrier.carrier}</h4>
                  <span className={`px-2 py-0.5 text-xs font-medium rounded ${
                    carrier.appetite === 'strong' ? 'bg-green-100 text-green-700' :
                    carrier.appetite === 'moderate' ? 'bg-yellow-100 text-yellow-700' :
                    carrier.appetite === 'limited' ? 'bg-orange-100 text-orange-700' :
                    'bg-red-100 text-red-700'
                  }`}>{carrier.appetite}</span>
                </div>
                {carrier.specialties && (
                  <p className="text-sm text-gray-600">Specialties: {carrier.specialties.join(', ')}</p>
                )}
                {carrier.concerns && (
                  <p className="text-sm text-orange-600 mt-1">Concern: {carrier.concerns}</p>
                )}
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Coverage Recommendations from Research */}
      {research.coverageRecommendations?.priorityCoverage?.length > 0 && (
        <CollapsibleSection
          title="Coverage Recommendations"
          icon={Shield}
          count={research.coverageRecommendations.priorityCoverage.length}
          expanded={expandedSections.coverageRec}
          onToggle={() => toggleSection('coverageRec')}
        >
          <div className="space-y-4">
            {research.coverageRecommendations.priorityCoverage.map((cov, idx) => (
              <div key={idx} className="p-4 border border-gray-200 rounded-lg">
                <div className="flex items-center justify-between mb-2">
                  <h4 className="font-semibold text-marsh-blue">{cov.line}</h4>
                  <span className="text-sm bg-marsh-blue/10 text-marsh-blue px-2 py-0.5 rounded">
                    Priority {cov.priority}
                  </span>
                </div>
                <p className="text-sm text-gray-600">{cov.rationale}</p>
                {cov.suggestedLimits && (
                  <p className="text-sm text-gray-500 mt-2">
                    <strong>Suggested Limits:</strong> {cov.suggestedLimits}
                  </p>
                )}
                {cov.keyCarriers?.length > 0 && (
                  <p className="text-sm text-gray-500 mt-1">
                    <strong>Key Carriers:</strong> {cov.keyCarriers.join(', ')}
                  </p>
                )}
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Alternative Risk Solutions */}
      {research.alternativeRiskSolutions && (
        <CollapsibleSection
          title="Alternative Risk Solutions"
          icon={Lightbulb}
          expanded={expandedSections.altRisk}
          onToggle={() => toggleSection('altRisk')}
        >
          <div className="grid md:grid-cols-2 gap-4">
            {research.alternativeRiskSolutions.captiveOptions?.viable && (
              <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
                <h4 className="font-medium text-green-900">Captive Insurance</h4>
                <p className="text-sm text-green-700 mt-1">{research.alternativeRiskSolutions.captiveOptions.rationale}</p>
                {research.alternativeRiskSolutions.captiveOptions.type && (
                  <p className="text-sm text-green-600 mt-2">Type: {research.alternativeRiskSolutions.captiveOptions.type}</p>
                )}
              </div>
            )}

            {research.alternativeRiskSolutions.parametricSolutions?.viable && (
              <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                <h4 className="font-medium text-blue-900">Parametric Solutions</h4>
                <p className="text-sm text-blue-700 mt-1">{research.alternativeRiskSolutions.parametricSolutions.structureOptions}</p>
              </div>
            )}
          </div>
        </CollapsibleSection>
      )}

      {/* Sources */}
      {research.sources?.length > 0 && (
        <CollapsibleSection
          title="Research Sources"
          icon={ExternalLink}
          count={research.sources.length}
          expanded={expandedSections.sources}
          onToggle={() => toggleSection('sources')}
        >
          <div className="space-y-2">
            {research.sources.map((source, idx) => (
              <div key={idx} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                <div>
                  <p className="font-medium text-gray-900">{source.title}</p>
                  <p className="text-sm text-gray-500">{source.type} • {source.relevance}</p>
                </div>
                {source.url && (
                  <a href={source.url} target="_blank" rel="noopener noreferrer"
                     className="text-marsh-blue hover:underline">
                    <ExternalLink className="w-4 h-4" />
                  </a>
                )}
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}
    </div>
  )
}

// Exports Tab Component
function ExportsTab({ meeting, onGeneratePowerPoint, onGeneratePodcast, processing, apiStatus }) {
  const [showPodcastOptions, setShowPodcastOptions] = useState(false)

  return (
    <div className="space-y-6">
      {/* PowerPoint Export */}
      <div className="border border-gray-200 rounded-xl p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 bg-orange-100 rounded-lg flex items-center justify-center">
            <FileSpreadsheet className="w-5 h-5 text-orange-600" />
          </div>
          <div>
            <h3 className="font-semibold text-gray-900">PowerPoint Presentation</h3>
            <p className="text-sm text-gray-500">Generate professional slide decks</p>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-4">
          <button
            onClick={() => onGeneratePowerPoint('internal')}
            disabled={processing.powerpoint}
            className="p-4 border-2 border-gray-200 rounded-lg hover:border-marsh-blue hover:bg-marsh-blue/5 transition-colors text-left disabled:opacity-50"
          >
            <h4 className="font-medium text-gray-900">Internal Version</h4>
            <p className="text-sm text-gray-500 mt-1">Detailed strategy for Marsh team and leadership</p>
            {processing.powerpoint && <Loader2 className="w-4 h-4 animate-spin mt-2" />}
          </button>

          <button
            onClick={() => onGeneratePowerPoint('external')}
            disabled={processing.powerpoint}
            className="p-4 border-2 border-gray-200 rounded-lg hover:border-marsh-blue hover:bg-marsh-blue/5 transition-colors text-left disabled:opacity-50"
          >
            <h4 className="font-medium text-gray-900">External Version</h4>
            <p className="text-sm text-gray-500 mt-1">Polished presentation for client/prospects</p>
            {processing.powerpoint && <Loader2 className="w-4 h-4 animate-spin mt-2" />}
          </button>
        </div>
      </div>

      {/* Podcast/Audio Summary */}
      <div className="border border-gray-200 rounded-xl p-6">
        <div className="flex items-center gap-3 mb-4">
          <div className="w-10 h-10 bg-purple-100 rounded-lg flex items-center justify-center">
            <Headphones className="w-5 h-5 text-purple-600" />
          </div>
          <div>
            <h3 className="font-semibold text-gray-900">Audio Summary</h3>
            <p className="text-sm text-gray-500">Generate a podcast-style audio briefing</p>
          </div>
        </div>

        {!apiStatus.elevenlabs ? (
          <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 text-yellow-700 text-sm">
            <AlertTriangle className="w-4 h-4 inline mr-2" />
            ElevenLabs API key required for audio generation. Add ELEVENLABS_API_KEY to your .env file.
          </div>
        ) : meeting.podcast ? (
          <div className="space-y-4">
            <audio src={meeting.podcast.downloadUrl} controls className="w-full" />
            <p className="text-sm text-gray-500">
              Generated: {new Date(meeting.podcast.generatedAt).toLocaleString()}
            </p>
          </div>
        ) : (
          <div>
            <button
              onClick={() => setShowPodcastOptions(!showPodcastOptions)}
              className="px-4 py-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 flex items-center gap-2"
            >
              <Headphones className="w-4 h-4" />
              Generate Audio Summary
            </button>

            {showPodcastOptions && (
              <div className="mt-4 grid md:grid-cols-2 gap-4">
                <button
                  onClick={() => onGeneratePodcast('female')}
                  disabled={processing.podcast}
                  className="p-4 border-2 border-gray-200 rounded-lg hover:border-purple-500 hover:bg-purple-50 transition-colors text-left disabled:opacity-50"
                >
                  <h4 className="font-medium text-gray-900">Female Voice</h4>
                  <p className="text-sm text-gray-500 mt-1">Professional female narrator</p>
                  {processing.podcast && <Loader2 className="w-4 h-4 animate-spin mt-2" />}
                </button>

                <button
                  onClick={() => onGeneratePodcast('male')}
                  disabled={processing.podcast}
                  className="p-4 border-2 border-gray-200 rounded-lg hover:border-purple-500 hover:bg-purple-50 transition-colors text-left disabled:opacity-50"
                >
                  <h4 className="font-medium text-gray-900">Male Voice</h4>
                  <p className="text-sm text-gray-500 mt-1">Professional male narrator</p>
                  {processing.podcast && <Loader2 className="w-4 h-4 animate-spin mt-2" />}
                </button>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Other Exports */}
      <div className="border border-gray-200 rounded-xl p-6">
        <h3 className="font-semibold text-gray-900 mb-4">Other Export Options</h3>
        <div className="flex flex-wrap gap-3">
          <a
            href={`/api/export/${meeting.id}/pdf`}
            className="px-4 py-2 border border-gray-200 rounded-lg text-gray-700 hover:bg-gray-50 flex items-center gap-2"
          >
            <Download className="w-4 h-4" />
            Export as PDF
          </a>
          <a
            href={`/api/export/${meeting.id}/text`}
            className="px-4 py-2 border border-gray-200 rounded-lg text-gray-700 hover:bg-gray-50 flex items-center gap-2"
          >
            <FileText className="w-4 h-4" />
            Export as Text
          </a>
        </div>
      </div>
    </div>
  )
}

// Collapsible Section Component
function CollapsibleSection({ title, icon: Icon, count, expanded, onToggle, children }) {
  return (
    <div className="border border-gray-200 rounded-xl overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between p-4 bg-gray-50 hover:bg-gray-100 transition-colors"
      >
        <div className="flex items-center gap-3">
          {Icon && <Icon className="w-5 h-5 text-gray-600" />}
          <span className="font-medium text-gray-900">{title}</span>
          {count !== undefined && (
            <span className="px-2 py-0.5 bg-gray-200 text-gray-600 text-xs font-medium rounded-full">
              {count}
            </span>
          )}
        </div>
        {expanded ? (
          <ChevronUp className="w-5 h-5 text-gray-400" />
        ) : (
          <ChevronDown className="w-5 h-5 text-gray-400" />
        )}
      </button>
      {expanded && (
        <div className="p-4 border-t border-gray-200">
          {children}
        </div>
      )}
    </div>
  )
}
