import React, { useState, useEffect, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  ArrowLeft, Play, FileText, Brain, Search, Download,
  Mail, FileSpreadsheet, Headphones, Shield, Clock,
  ChevronDown, ChevronUp, ExternalLink, AlertTriangle,
  Check, Loader2, Building, Users, TrendingUp, Target,
  Briefcase, Globe, AlertCircle, Lightbulb, Sparkles
} from 'lucide-react'
import { api } from '../utils/api'
import { useMeetings } from '../contexts/MeetingsContext'

const TABS = {
  OVERVIEW: 'overview',
  TRANSCRIPT: 'transcript',
  ANALYSIS: 'analysis',
  RFP: 'rfp',
  RESEARCH: 'research',
  EXPORTS: 'exports'
}

export default function MeetingDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const { getMeeting, apiStatus } = useMeetings()

  const [meeting, setMeeting] = useState(null)
  const [loading, setLoading] = useState(true)
  const [activeTab, setActiveTab] = useState(TABS.OVERVIEW)
  const [processing, setProcessing] = useState({
    transcription: false,
    analysis: false,
    research: false,
    powerpoint: false,
    podcast: false
  })
  const [error, setError] = useState(null)
  const [expandedSections, setExpandedSections] = useState({})

  // Fetch meeting data
  const fetchMeeting = useCallback(async () => {
    try {
      setLoading(true)
      const data = await getMeeting(id)
      setMeeting(data)

      // Auto-select RFP tab for RFP meetings
      if (data.meetingType === 'Fact-Finding Session (RFP)' && data.analysis) {
        setActiveTab(TABS.RFP)
      } else if (data.analysis) {
        setActiveTab(TABS.ANALYSIS)
      }
    } catch (err) {
      setError('Failed to load meeting')
      console.error(err)
    } finally {
      setLoading(false)
    }
  }, [id, getMeeting])

  useEffect(() => {
    fetchMeeting()
  }, [fetchMeeting])

  // Transcribe meeting
  const handleTranscribe = async () => {
    try {
      setProcessing(prev => ({ ...prev, transcription: true }))
      setError(null)
      await api.transcribeMeeting(id)
      await fetchMeeting()
    } catch (err) {
      setError('Transcription failed: ' + err.message)
    } finally {
      setProcessing(prev => ({ ...prev, transcription: false }))
    }
  }

  // Analyze meeting
  const handleAnalyze = async () => {
    try {
      setProcessing(prev => ({ ...prev, analysis: true }))
      setError(null)
      await api.analyzeMeeting(id)
      await fetchMeeting()
    } catch (err) {
      setError('Analysis failed: ' + err.message)
    } finally {
      setProcessing(prev => ({ ...prev, analysis: false }))
    }
  }

  // Deep Research
  const handleDeepResearch = async () => {
    try {
      setProcessing(prev => ({ ...prev, research: true }))
      setError(null)
      await api.runDeepResearch(id)
      await fetchMeeting()
      setActiveTab(TABS.RESEARCH)
    } catch (err) {
      setError('Deep Research failed: ' + err.message)
    } finally {
      setProcessing(prev => ({ ...prev, research: false }))
    }
  }

  // Generate PowerPoint
  const handleGeneratePowerPoint = async (type) => {
    try {
      setProcessing(prev => ({ ...prev, powerpoint: true }))
      setError(null)
      const result = await api.generatePowerPoint(id, type)
      if (result.downloadUrl) {
        window.open(result.downloadUrl, '_blank')
      }
    } catch (err) {
      setError('PowerPoint generation failed: ' + err.message)
    } finally {
      setProcessing(prev => ({ ...prev, powerpoint: false }))
    }
  }

  // Generate Podcast
  const handleGeneratePodcast = async (voiceType) => {
    try {
      setProcessing(prev => ({ ...prev, podcast: true }))
      setError(null)
      const result = await api.generatePodcast(id, voiceType)
      await fetchMeeting()
    } catch (err) {
      setError('Podcast generation failed: ' + err.message)
    } finally {
      setProcessing(prev => ({ ...prev, podcast: false }))
    }
  }

  // Email summary
  const handleEmailSummary = () => {
    if (!meeting?.analysis) return

    const subject = encodeURIComponent(`Meeting Summary: ${meeting.title}`)
    const body = encodeURIComponent(`
Meeting Summary: ${meeting.title}
Date: ${new Date(meeting.createdAt).toLocaleDateString()}
Type: ${meeting.meetingType}
${meeting.clientName ? `Client: ${meeting.clientName}` : ''}

SUMMARY:
${meeting.analysis.summary || 'No summary available'}

ACTION ITEMS:
${meeting.analysis.actionItems?.map(item =>
  `- ${item.task} (Owner: ${item.owner || 'TBD'}, Due: ${item.deadline || 'TBD'})`
).join('\n') || 'None'}

---
Generated by D&W Holdings Meeting Analyzer
    `)

    window.location.href = `mailto:?subject=${subject}&body=${body}`
  }

  // Toggle section expansion
  const toggleSection = (section) => {
    setExpandedSections(prev => ({ ...prev, [section]: !prev[section] }))
  }

  // Format helpers
  const formatDate = (dateStr) => new Date(dateStr).toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
  })

  const formatDuration = (seconds) => {
    if (!seconds) return '—'
    const mins = Math.floor(seconds / 60)
    const secs = Math.floor(seconds % 60)
    return `${mins}:${secs.toString().padStart(2, '0')}`
  }

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen">
        <div className="spinner spinner-lg mb-4" />
        <span className="text-gray-500 font-medium">Loading meeting...</span>
      </div>
    )
  }

  if (!meeting) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-8">
        <div className="premium-card-static p-12 text-center">
          <div className="w-16 h-16 bg-red-100 rounded-2xl flex items-center justify-center mx-auto mb-4">
            <AlertTriangle className="w-8 h-8 text-red-500" />
          </div>
          <h2 className="text-xl font-semibold text-gray-900 mb-2">Meeting Not Found</h2>
          <button onClick={() => navigate('/')} className="text-dw-teal hover:text-dw-teal-dark font-medium">
            Return to Dashboard
          </button>
        </div>
      </div>
    )
  }

  const isRFP = meeting.meetingType === 'Fact-Finding Session (RFP)'
  const hasTranscript = !!meeting.transcript
  const hasAnalysis = !!meeting.analysis
  const hasResearch = !!meeting.deepResearch

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
      {/* Header */}
      <div className="mb-8">
        <button
          onClick={() => navigate('/')}
          className="flex items-center gap-2 text-gray-500 hover:text-dw-teal transition-colors mb-4 font-medium"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Dashboard
        </button>

        <div className="flex items-start justify-between">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <h1 className="text-2xl font-bold text-gray-900">{meeting.title}</h1>
              {isRFP && (
                <span className="badge badge-rfp">
                  <FileSpreadsheet className="w-3.5 h-3.5" />
                  RFP Session
                </span>
              )}
              <span className={`badge ${
                meeting.confidentiality === 'Confidential' ? 'confidential-confidential' :
                meeting.confidentiality === 'Highly Confidential' ? 'confidential-highly-confidential' :
                'confidential-internal'
              }`}>
                <Shield className="w-3 h-3" />
                {meeting.confidentiality}
              </span>
            </div>
            <div className="flex items-center gap-5 text-sm text-gray-500">
              <span className="flex items-center gap-1.5">
                <Clock className="w-4 h-4" />
                {formatDate(meeting.createdAt)}
              </span>
              <span className="font-medium">{formatDuration(meeting.duration)}</span>
              {meeting.clientName && (
                <span className="flex items-center gap-1.5 font-medium text-gray-600">
                  <Building className="w-4 h-4" />
                  {meeting.clientName}
                </span>
              )}
            </div>
          </div>

          {/* Quick Actions */}
          <div className="flex items-center gap-3">
            {hasAnalysis && (
              <button
                onClick={handleEmailSummary}
                className="btn-premium btn-secondary"
              >
                <Mail className="w-4 h-4" />
                Email Summary
              </button>
            )}
            {hasAnalysis && isRFP && !hasResearch && (
              <button
                onClick={handleDeepResearch}
                disabled={processing.research}
                className="btn-premium bg-purple-600 hover:bg-purple-700 text-white"
              >
                {processing.research ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <Search className="w-4 h-4" />
                )}
                Deep Research
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Error Alert */}
      {error && (
        <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-xl flex items-center gap-3 text-red-700">
          <AlertTriangle className="w-5 h-5 flex-shrink-0" />
          <span className="flex-1">{error}</span>
          <button onClick={() => setError(null)} className="text-red-500 hover:text-red-700 font-bold">×</button>
        </div>
      )}

      {/* Processing Pipeline */}
      {!hasAnalysis && (
        <div className="premium-card-static p-6 mb-8">
          <h2 className="text-lg font-bold text-gray-900 mb-5">Processing Pipeline</h2>
          <div className="flex items-center gap-4">
            {/* Step 1: Transcribe */}
            <div className={`flex-1 p-5 rounded-xl border-2 transition-all ${
              hasTranscript ? 'border-emerald-400 bg-emerald-50' :
              processing.transcription ? 'border-amber-400 bg-amber-50' :
              'border-gray-200 bg-gray-50'
            }`}>
              <div className="flex items-center gap-3">
                {hasTranscript ? (
                  <div className="w-10 h-10 bg-emerald-500 rounded-xl flex items-center justify-center">
                    <Check className="w-5 h-5 text-white" />
                  </div>
                ) : processing.transcription ? (
                  <div className="w-10 h-10 bg-amber-500 rounded-xl flex items-center justify-center">
                    <Loader2 className="w-5 h-5 text-white animate-spin" />
                  </div>
                ) : (
                  <div className="w-10 h-10 bg-gray-200 rounded-xl flex items-center justify-center">
                    <FileText className="w-5 h-5 text-gray-500" />
                  </div>
                )}
                <div>
                  <h3 className="font-semibold text-gray-900">1. Transcribe</h3>
                  <p className="text-sm text-gray-500">Convert audio to text</p>
                </div>
              </div>
              {!hasTranscript && !processing.transcription && (
                <button
                  onClick={handleTranscribe}
                  disabled={!apiStatus.openai}
                  className="mt-4 w-full btn-premium btn-primary"
                >
                  Start Transcription
                </button>
              )}
            </div>

            <ChevronDown className="w-6 h-6 text-gray-300 rotate-[-90deg]" />

            {/* Step 2: Analyze */}
            <div className={`flex-1 p-5 rounded-xl border-2 transition-all ${
              hasAnalysis ? 'border-emerald-400 bg-emerald-50' :
              processing.analysis ? 'border-amber-400 bg-amber-50' :
              hasTranscript ? 'border-gray-200 bg-gray-50' : 'border-gray-100 bg-gray-50/50 opacity-50'
            }`}>
              <div className="flex items-center gap-3">
                {hasAnalysis ? (
                  <div className="w-10 h-10 bg-emerald-500 rounded-xl flex items-center justify-center">
                    <Check className="w-5 h-5 text-white" />
                  </div>
                ) : processing.analysis ? (
                  <div className="w-10 h-10 bg-amber-500 rounded-xl flex items-center justify-center">
                    <Loader2 className="w-5 h-5 text-white animate-spin" />
                  </div>
                ) : (
                  <div className="w-10 h-10 bg-gray-200 rounded-xl flex items-center justify-center">
                    <Brain className="w-5 h-5 text-gray-500" />
                  </div>
                )}
                <div>
                  <h3 className="font-semibold text-gray-900">2. Analyze</h3>
                  <p className="text-sm text-gray-500">AI-powered insights</p>
                </div>
              </div>
              {hasTranscript && !hasAnalysis && !processing.analysis && (
                <button
                  onClick={handleAnalyze}
                  disabled={!apiStatus.anthropic}
                  className="mt-4 w-full btn-premium btn-primary"
                >
                  Start Analysis
                </button>
              )}
            </div>

            {isRFP && (
              <>
                <ChevronDown className="w-6 h-6 text-gray-300 rotate-[-90deg]" />

                {/* Step 3: Deep Research (RFP only) */}
                <div className={`flex-1 p-5 rounded-xl border-2 transition-all ${
                  hasResearch ? 'border-emerald-400 bg-emerald-50' :
                  processing.research ? 'border-purple-400 bg-purple-50' :
                  hasAnalysis ? 'border-gray-200 bg-gray-50' : 'border-gray-100 bg-gray-50/50 opacity-50'
                }`}>
                  <div className="flex items-center gap-3">
                    {hasResearch ? (
                      <div className="w-10 h-10 bg-emerald-500 rounded-xl flex items-center justify-center">
                        <Check className="w-5 h-5 text-white" />
                      </div>
                    ) : processing.research ? (
                      <div className="w-10 h-10 bg-purple-500 rounded-xl flex items-center justify-center">
                        <Loader2 className="w-5 h-5 text-white animate-spin" />
                      </div>
                    ) : (
                      <div className="w-10 h-10 bg-gray-200 rounded-xl flex items-center justify-center">
                        <Search className="w-5 h-5 text-gray-500" />
                      </div>
                    )}
                    <div>
                      <h3 className="font-semibold text-gray-900">3. Deep Research</h3>
                      <p className="text-sm text-gray-500">Market intelligence</p>
                    </div>
                  </div>
                  {hasAnalysis && !hasResearch && !processing.research && (
                    <button
                      onClick={handleDeepResearch}
                      className="mt-4 w-full btn-premium bg-purple-600 hover:bg-purple-700 text-white"
                    >
                      Run Deep Research
                    </button>
                  )}
                </div>
              </>
            )}
          </div>
        </div>
      )}

      {/* Tabs */}
      <div className="premium-card-static overflow-hidden">
        <div className="border-b border-gray-100">
          <nav className="flex -mb-px">
            {[
              { id: TABS.OVERVIEW, label: 'Overview', icon: FileText },
              { id: TABS.TRANSCRIPT, label: 'Transcript', icon: FileText, disabled: !hasTranscript },
              { id: TABS.ANALYSIS, label: 'Analysis', icon: Brain, disabled: !hasAnalysis },
              ...(isRFP ? [{ id: TABS.RFP, label: 'RFP Builder', icon: FileSpreadsheet, disabled: !hasAnalysis }] : []),
              { id: TABS.RESEARCH, label: 'Deep Research', icon: Search, disabled: !hasResearch },
              { id: TABS.EXPORTS, label: 'Exports', icon: Download, disabled: !hasAnalysis }
            ].map(tab => (
              <button
                key={tab.id}
                onClick={() => !tab.disabled && setActiveTab(tab.id)}
                disabled={tab.disabled}
                className={`flex items-center gap-2 px-6 py-4 text-sm font-semibold border-b-2 transition-all ${
                  activeTab === tab.id
                    ? 'border-dw-teal text-dw-teal'
                    : tab.disabled
                    ? 'border-transparent text-gray-300 cursor-not-allowed'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
              >
                <tab.icon className="w-4 h-4" />
                {tab.label}
              </button>
            ))}
          </nav>
        </div>

        <div className="p-6">
          {/* Overview Tab */}
          {activeTab === TABS.OVERVIEW && (
            <OverviewTab meeting={meeting} />
          )}

          {/* Transcript Tab */}
          {activeTab === TABS.TRANSCRIPT && hasTranscript && (
            <TranscriptTab transcript={meeting.transcript} />
          )}

          {/* Analysis Tab */}
          {activeTab === TABS.ANALYSIS && hasAnalysis && (
            <AnalysisTab
              analysis={meeting.analysis}
              expandedSections={expandedSections}
              toggleSection={toggleSection}
            />
          )}

          {/* RFP Tab */}
          {activeTab === TABS.RFP && isRFP && hasAnalysis && (
            <RfpTab
              meeting={meeting}
              expandedSections={expandedSections}
              toggleSection={toggleSection}
              onDeepResearch={handleDeepResearch}
              processing={processing}
            />
          )}

          {/* Research Tab */}
          {activeTab === TABS.RESEARCH && hasResearch && (
            <ResearchTab
              research={meeting.deepResearch}
              expandedSections={expandedSections}
              toggleSection={toggleSection}
            />
          )}

          {/* Exports Tab */}
          {activeTab === TABS.EXPORTS && hasAnalysis && (
            <ExportsTab
              meeting={meeting}
              onGeneratePowerPoint={handleGeneratePowerPoint}
              onGeneratePodcast={handleGeneratePodcast}
              processing={processing}
              apiStatus={apiStatus}
            />
          )}
        </div>
      </div>
    </div>
  )
}

// Overview Tab Component
function OverviewTab({ meeting }) {
  return (
    <div className="space-y-6">
      {/* Audio Player */}
      <div>
        <h3 className="text-sm font-semibold text-gray-700 mb-3">Recording</h3>
        <audio src={meeting.audioPath} controls className="w-full" />
      </div>

      {/* Meeting Info */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-gray-50 rounded-xl p-4">
          <p className="text-sm text-gray-500 mb-1">Type</p>
          <p className="font-semibold text-gray-900">{meeting.meetingType}</p>
        </div>
        <div className="bg-gray-50 rounded-xl p-4">
          <p className="text-sm text-gray-500 mb-1">Status</p>
          <p className="font-semibold text-gray-900 capitalize">{meeting.status}</p>
        </div>
        <div className="bg-gray-50 rounded-xl p-4">
          <p className="text-sm text-gray-500 mb-1">Confidentiality</p>
          <p className="font-semibold text-gray-900">{meeting.confidentiality}</p>
        </div>
        <div className="bg-gray-50 rounded-xl p-4">
          <p className="text-sm text-gray-500 mb-1">Duration</p>
          <p className="font-semibold text-gray-900">{meeting.duration ? `${Math.floor(meeting.duration / 60)}:${Math.floor(meeting.duration % 60).toString().padStart(2, '0')}` : '—'}</p>
        </div>
      </div>

      {/* Summary Preview */}
      {meeting.analysis?.summary && (
        <div>
          <h3 className="text-sm font-semibold text-gray-700 mb-3">Summary</h3>
          <p className="text-gray-600 bg-gray-50 rounded-xl p-5 leading-relaxed">{meeting.analysis.summary}</p>
        </div>
      )}
    </div>
  )
}

// Transcript Tab Component
function TranscriptTab({ transcript }) {
  return (
    <div>
      <div className="flex items-center justify-between mb-4">
        <h3 className="font-semibold text-gray-900">Full Transcript</h3>
        <span className="text-sm text-gray-500 bg-gray-100 px-3 py-1 rounded-full">
          Duration: {Math.floor(transcript.duration / 60)}:{Math.floor(transcript.duration % 60).toString().padStart(2, '0')}
        </span>
      </div>

      {transcript.segments?.length > 0 ? (
        <div className="space-y-3 max-h-[600px] overflow-y-auto pr-2">
          {transcript.segments.map((segment, idx) => (
            <div key={idx} className="flex gap-3 p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors">
              <span className="text-xs text-dw-teal font-mono w-12 flex-shrink-0 pt-0.5 font-semibold">
                {segment.timestamp}
              </span>
              <p className="text-gray-700">{segment.text}</p>
            </div>
          ))}
        </div>
      ) : (
        <div className="bg-gray-50 rounded-xl p-5 whitespace-pre-wrap text-gray-700 leading-relaxed">
          {transcript.text}
        </div>
      )}
    </div>
  )
}

// Analysis Tab Component
function AnalysisTab({ analysis, expandedSections, toggleSection }) {
  return (
    <div className="space-y-6">
      {/* Summary */}
      <div className="bg-gradient-to-br from-dw-navy/5 to-dw-teal/5 rounded-xl p-6 border border-dw-teal/10">
        <h3 className="font-bold text-dw-navy mb-3 flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-dw-gold" />
          Executive Summary
        </h3>
        <p className="text-gray-700 leading-relaxed">{analysis.summary}</p>
      </div>

      {/* Key Topics */}
      {analysis.keyTopics?.length > 0 && (
        <CollapsibleSection
          title="Key Topics"
          icon={Target}
          count={analysis.keyTopics.length}
          expanded={expandedSections.keyTopics}
          onToggle={() => toggleSection('keyTopics')}
        >
          <div className="space-y-3">
            {analysis.keyTopics.map((topic, idx) => (
              <div key={idx} className="flex items-start gap-3 p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors">
                <span className={`px-2.5 py-1 text-xs font-semibold rounded-lg ${
                  topic.importance === 'high' ? 'bg-red-100 text-red-700' :
                  topic.importance === 'medium' ? 'bg-amber-100 text-amber-700' :
                  'bg-emerald-100 text-emerald-700'
                }`}>{topic.importance}</span>
                <div>
                  <h4 className="font-semibold text-gray-900">{topic.topic}</h4>
                  <p className="text-sm text-gray-600 mt-1">{topic.description}</p>
                </div>
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Action Items */}
      {analysis.actionItems?.length > 0 && (
        <CollapsibleSection
          title="Action Items"
          icon={Check}
          count={analysis.actionItems.length}
          expanded={expandedSections.actionItems !== false}
          onToggle={() => toggleSection('actionItems')}
        >
          <div className="space-y-3">
            {analysis.actionItems.map((item, idx) => (
              <div key={idx} className="p-4 border border-gray-200 rounded-xl hover:border-dw-teal/30 transition-colors">
                <div className="flex items-start justify-between gap-4">
                  <div className="flex-1">
                    <p className="font-semibold text-gray-900">{item.task}</p>
                    {item.notes && <p className="text-sm text-gray-500 mt-1">{item.notes}</p>}
                  </div>
                  <span className={`px-2.5 py-1 text-xs font-semibold rounded-lg ${
                    item.priority === 'high' ? 'bg-red-100 text-red-700' :
                    item.priority === 'medium' ? 'bg-amber-100 text-amber-700' :
                    'bg-gray-100 text-gray-700'
                  }`}>{item.priority}</span>
                </div>
                <div className="flex items-center gap-5 mt-3 text-sm text-gray-500">
                  <span className="flex items-center gap-1.5">
                    <Users className="w-3.5 h-3.5" />
                    {item.owner || 'TBD'}
                  </span>
                  <span className="flex items-center gap-1.5">
                    <Clock className="w-3.5 h-3.5" />
                    {item.deadline || 'TBD'}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Business Implications */}
      {analysis.businessImplications?.length > 0 && (
        <CollapsibleSection
          title="Business Implications"
          icon={TrendingUp}
          count={analysis.businessImplications.length}
          expanded={expandedSections.implications}
          onToggle={() => toggleSection('implications')}
        >
          <div className="space-y-3">
            {analysis.businessImplications.map((item, idx) => (
              <div key={idx} className="p-4 bg-blue-50 rounded-xl border border-blue-100">
                <h4 className="font-semibold text-blue-900">{item.implication}</h4>
                <p className="text-sm text-blue-700 mt-1">{item.impact}</p>
                {item.recommendation && (
                  <p className="text-sm text-blue-600 mt-2 flex items-center gap-1.5">
                    <Lightbulb className="w-3.5 h-3.5" />
                    {item.recommendation}
                  </p>
                )}
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Risk Exposures */}
      {analysis.riskExposures?.length > 0 && (
        <CollapsibleSection
          title="Risk Exposures Identified"
          icon={AlertCircle}
          count={analysis.riskExposures.length}
          expanded={expandedSections.risks}
          onToggle={() => toggleSection('risks')}
        >
          <div className="space-y-3">
            {analysis.riskExposures.map((risk, idx) => (
              <div key={idx} className="flex items-start gap-3 p-4 bg-gray-50 rounded-xl">
                <span className={`px-2.5 py-1 text-xs font-semibold rounded-lg ${
                  risk.severity === 'high' ? 'bg-red-100 text-red-700' :
                  risk.severity === 'medium' ? 'bg-amber-100 text-amber-700' :
                  'bg-emerald-100 text-emerald-700'
                }`}>{risk.severity}</span>
                <div>
                  <h4 className="font-semibold text-gray-900">{risk.exposure}</h4>
                  {risk.coverageType && (
                    <p className="text-sm text-gray-500 mt-1">Coverage: {risk.coverageType}</p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}
    </div>
  )
}

// RFP Tab Component
function RfpTab({ meeting, expandedSections, toggleSection, onDeepResearch, processing }) {
  const rfpData = meeting.rfpData
  const factFinding = rfpData?.factFindingSummary || {}
  const rfpDraft = rfpData?.rfpDraft || {}

  return (
    <div className="space-y-6">
      {/* Deep Research CTA */}
      {!meeting.deepResearch && (
        <div className="bg-gradient-to-r from-purple-50 to-purple-100 border border-purple-200 rounded-2xl p-6">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-lg font-bold text-purple-900">Ready for Deep Research?</h3>
              <p className="text-purple-700 mt-1">
                Run comprehensive market research including carrier appetite, regional risks, and competitive intelligence.
              </p>
            </div>
            <button
              onClick={onDeepResearch}
              disabled={processing.research}
              className="btn-premium bg-purple-600 hover:bg-purple-700 text-white px-6"
            >
              {processing.research ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                <Search className="w-5 h-5" />
              )}
              Run Deep Research
            </button>
          </div>
        </div>
      )}

      {/* Client Profile */}
      <div className="premium-card-static overflow-hidden">
        <div className="bg-gradient-to-r from-gray-50 to-gray-100 px-6 py-4 border-b border-gray-200">
          <h3 className="font-bold text-gray-900 flex items-center gap-2">
            <Building className="w-5 h-5 text-dw-teal" />
            Client Profile
          </h3>
        </div>
        <div className="p-6">
          <div className="grid grid-cols-2 md:grid-cols-3 gap-6">
            <div>
              <p className="text-sm text-gray-500 mb-1">Client Name</p>
              <p className="font-semibold text-gray-900">{factFinding.clientName || meeting.clientName || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-1">Industry</p>
              <p className="font-semibold text-gray-900">{factFinding.industry || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-1">Location</p>
              <p className="font-semibold text-gray-900">{factFinding.location || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-1">Employees</p>
              <p className="font-semibold text-gray-900">{factFinding.employeeCount || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-1">Current Broker</p>
              <p className="font-semibold text-gray-900">{factFinding.currentProgram?.incumbent || 'N/A'}</p>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-1">Renewal Date</p>
              <p className="font-semibold text-gray-900">{factFinding.currentProgram?.expirationDate || 'N/A'}</p>
            </div>
          </div>
        </div>
      </div>

      {/* Pain Points */}
      {factFinding.painPoints?.length > 0 && (
        <CollapsibleSection
          title="Pain Points Identified"
          icon={AlertTriangle}
          count={factFinding.painPoints.length}
          expanded={expandedSections.painPoints !== false}
          onToggle={() => toggleSection('painPoints')}
        >
          <div className="space-y-3">
            {factFinding.painPoints.map((point, idx) => (
              <div key={idx} className="p-4 bg-amber-50 border border-amber-100 rounded-xl">
                <div className="flex items-start gap-3">
                  <span className={`px-2.5 py-1 text-xs font-semibold rounded-lg ${
                    point.severity === 'high' ? 'bg-red-100 text-red-700' :
                    point.severity === 'medium' ? 'bg-amber-100 text-amber-700' :
                    'bg-emerald-100 text-emerald-700'
                  }`}>{point.severity}</span>
                  <div>
                    <h4 className="font-semibold text-gray-900">{point.issue}</h4>
                    {point.impact && <p className="text-sm text-gray-600 mt-1">{point.impact}</p>}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Coverage Recommendations */}
      {rfpDraft.recommendedCoverage?.length > 0 && (
        <CollapsibleSection
          title="Recommended Coverage Lines"
          icon={Shield}
          count={rfpDraft.recommendedCoverage.length}
          expanded={expandedSections.coverage !== false}
          onToggle={() => toggleSection('coverage')}
        >
          <div className="space-y-4">
            {rfpDraft.recommendedCoverage.map((coverage, idx) => (
              <div key={idx} className="p-5 border border-gray-200 rounded-xl hover:border-dw-teal/30 transition-colors">
                <h4 className="font-bold text-dw-teal">{coverage.line}</h4>
                <p className="text-sm text-gray-600 mt-2">{coverage.rationale}</p>
                {coverage.considerations && (
                  <p className="text-sm text-gray-500 mt-2 italic">{coverage.considerations}</p>
                )}
                {coverage.marketingApproach && (
                  <p className="text-sm text-dw-navy mt-2">
                    <strong>Approach:</strong> {coverage.marketingApproach}
                  </p>
                )}
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Cross-Sell Opportunities - D&W Holdings Service Lines */}
      {meeting.crossSellOpportunities?.length > 0 && (
        <div className="bg-gradient-to-r from-dw-navy to-dw-navy-light rounded-2xl p-6 text-white">
          <h3 className="font-bold text-lg mb-5 flex items-center gap-2">
            <Briefcase className="w-5 h-5 text-dw-gold" />
            D&W Holdings Service Lines
          </h3>
          <div className="grid md:grid-cols-3 gap-4">
            {meeting.crossSellOpportunities.map((opp, idx) => {
              // Map old company names to new division names
              const divisionName = {
                'Mercer': 'Benefits & Consulting Division',
                'Guy Carpenter': 'Risk Capital Solutions Division',
                'Oliver Wyman': 'Strategic Advisory Division'
              }[opp.company] || opp.company

              return (
                <div key={idx} className="bg-white/10 rounded-xl p-4 backdrop-blur-sm">
                  <h4 className="font-bold text-dw-gold">{divisionName}</h4>
                  <p className="text-sm opacity-80 mt-1">{opp.focus}</p>
                  {opp.opportunities?.[0] && (
                    <p className="text-sm mt-2 text-white/90">{opp.opportunities[0].rationale || opp.opportunities[0].service}</p>
                  )}
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* RFP Draft Executive Summary */}
      {rfpDraft.executiveSummary && (
        <div className="bg-gray-50 rounded-xl p-6">
          <h3 className="font-bold text-gray-900 mb-3">Draft Executive Summary</h3>
          <p className="text-gray-700 leading-relaxed whitespace-pre-wrap">{rfpDraft.executiveSummary}</p>
        </div>
      )}

      {/* D&W Holdings Value Proposition */}
      {rfpDraft.marshValueProposition && (
        <CollapsibleSection
          title="D&W Holdings Value Proposition"
          icon={Globe}
          expanded={expandedSections.valueProp}
          onToggle={() => toggleSection('valueProp')}
        >
          <div className="grid md:grid-cols-2 gap-4">
            {Object.entries(rfpDraft.marshValueProposition).map(([key, value]) => (
              value && (
                <div key={key} className="p-4 bg-gradient-to-br from-dw-navy/5 to-dw-teal/5 rounded-xl border border-dw-teal/10">
                  <h4 className="font-semibold text-dw-navy capitalize">{key.replace(/([A-Z])/g, ' $1')}</h4>
                  <p className="text-sm text-gray-600 mt-1">{value}</p>
                </div>
              )
            ))}
          </div>
        </CollapsibleSection>
      )}
    </div>
  )
}

// Research Tab Component
function ResearchTab({ research, expandedSections, toggleSection }) {
  const brief = research.executiveBrief || {}

  return (
    <div className="space-y-6">
      {/* Executive Brief */}
      <div className="bg-gradient-to-br from-purple-50 to-purple-100 border border-purple-200 rounded-2xl p-6">
        <h3 className="font-bold text-purple-900 mb-5 flex items-center gap-2">
          <Search className="w-5 h-5" />
          Executive Research Brief
        </h3>

        {brief.keyFindings?.length > 0 && (
          <div className="mb-5">
            <h4 className="font-semibold text-purple-800 mb-3">Key Findings</h4>
            <ul className="space-y-2">
              {brief.keyFindings.map((finding, idx) => (
                <li key={idx} className="text-purple-700 flex items-start gap-2">
                  <span className="w-1.5 h-1.5 bg-purple-500 rounded-full mt-2 flex-shrink-0" />
                  {finding}
                </li>
              ))}
            </ul>
          </div>
        )}

        {brief.criticalRisks?.length > 0 && (
          <div className="mb-5">
            <h4 className="font-semibold text-purple-800 mb-3">Critical Risks</h4>
            <ul className="space-y-2">
              {brief.criticalRisks.map((risk, idx) => (
                <li key={idx} className="text-purple-700 flex items-start gap-2">
                  <span className="w-1.5 h-1.5 bg-red-500 rounded-full mt-2 flex-shrink-0" />
                  {risk}
                </li>
              ))}
            </ul>
          </div>
        )}

        {brief.competitivePosition && (
          <div>
            <h4 className="font-semibold text-purple-800 mb-2">Competitive Position</h4>
            <p className="text-purple-700">{brief.competitivePosition}</p>
          </div>
        )}
      </div>

      {/* Market Intelligence */}
      {research.marketIntelligence && (
        <CollapsibleSection
          title="Market Intelligence"
          icon={TrendingUp}
          expanded={expandedSections.market}
          onToggle={() => toggleSection('market')}
        >
          <div className="space-y-4">
            {research.marketIntelligence.carrierAppetite?.map((carrier, idx) => (
              <div key={idx} className="p-4 border border-gray-200 rounded-xl hover:border-dw-teal/30 transition-colors">
                <div className="flex items-center justify-between mb-2">
                  <h4 className="font-semibold text-gray-900">{carrier.carrier}</h4>
                  <span className={`px-2.5 py-1 text-xs font-semibold rounded-lg ${
                    carrier.appetite === 'strong' ? 'bg-emerald-100 text-emerald-700' :
                    carrier.appetite === 'moderate' ? 'bg-amber-100 text-amber-700' :
                    carrier.appetite === 'limited' ? 'bg-orange-100 text-orange-700' :
                    'bg-red-100 text-red-700'
                  }`}>{carrier.appetite}</span>
                </div>
                {carrier.specialties && (
                  <p className="text-sm text-gray-600">Specialties: {carrier.specialties.join(', ')}</p>
                )}
                {carrier.concerns && (
                  <p className="text-sm text-orange-600 mt-1 flex items-center gap-1">
                    <AlertTriangle className="w-3.5 h-3.5" />
                    {carrier.concerns}
                  </p>
                )}
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Coverage Recommendations from Research */}
      {research.coverageRecommendations?.priorityCoverage?.length > 0 && (
        <CollapsibleSection
          title="Coverage Recommendations"
          icon={Shield}
          count={research.coverageRecommendations.priorityCoverage.length}
          expanded={expandedSections.coverageRec}
          onToggle={() => toggleSection('coverageRec')}
        >
          <div className="space-y-4">
            {research.coverageRecommendations.priorityCoverage.map((cov, idx) => (
              <div key={idx} className="p-5 border border-gray-200 rounded-xl">
                <div className="flex items-center justify-between mb-2">
                  <h4 className="font-bold text-dw-teal">{cov.line}</h4>
                  <span className="text-sm bg-dw-teal/10 text-dw-teal px-3 py-1 rounded-full font-semibold">
                    Priority {cov.priority}
                  </span>
                </div>
                <p className="text-sm text-gray-600">{cov.rationale}</p>
                {cov.suggestedLimits && (
                  <p className="text-sm text-gray-500 mt-2">
                    <strong>Suggested Limits:</strong> {cov.suggestedLimits}
                  </p>
                )}
                {cov.keyCarriers?.length > 0 && (
                  <p className="text-sm text-gray-500 mt-1">
                    <strong>Key Carriers:</strong> {cov.keyCarriers.join(', ')}
                  </p>
                )}
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}

      {/* Alternative Risk Solutions */}
      {research.alternativeRiskSolutions && (
        <CollapsibleSection
          title="Alternative Risk Solutions"
          icon={Lightbulb}
          expanded={expandedSections.altRisk}
          onToggle={() => toggleSection('altRisk')}
        >
          <div className="grid md:grid-cols-2 gap-4">
            {research.alternativeRiskSolutions.captiveOptions?.viable && (
              <div className="p-5 bg-emerald-50 border border-emerald-200 rounded-xl">
                <h4 className="font-semibold text-emerald-900">Captive Insurance</h4>
                <p className="text-sm text-emerald-700 mt-2">{research.alternativeRiskSolutions.captiveOptions.rationale}</p>
                {research.alternativeRiskSolutions.captiveOptions.type && (
                  <p className="text-sm text-emerald-600 mt-2">Type: {research.alternativeRiskSolutions.captiveOptions.type}</p>
                )}
              </div>
            )}

            {research.alternativeRiskSolutions.parametricSolutions?.viable && (
              <div className="p-5 bg-blue-50 border border-blue-200 rounded-xl">
                <h4 className="font-semibold text-blue-900">Parametric Solutions</h4>
                <p className="text-sm text-blue-700 mt-2">{research.alternativeRiskSolutions.parametricSolutions.structureOptions}</p>
              </div>
            )}
          </div>
        </CollapsibleSection>
      )}

      {/* Sources */}
      {research.sources?.length > 0 && (
        <CollapsibleSection
          title="Research Sources"
          icon={ExternalLink}
          count={research.sources.length}
          expanded={expandedSections.sources}
          onToggle={() => toggleSection('sources')}
        >
          <div className="space-y-2">
            {research.sources.map((source, idx) => (
              <div key={idx} className="flex items-center justify-between p-4 bg-gray-50 rounded-xl hover:bg-gray-100 transition-colors">
                <div>
                  <p className="font-semibold text-gray-900">{source.title}</p>
                  <p className="text-sm text-gray-500">{source.type} • {source.relevance}</p>
                </div>
                {source.url && (
                  <a href={source.url} target="_blank" rel="noopener noreferrer"
                     className="text-dw-teal hover:text-dw-teal-dark transition-colors">
                    <ExternalLink className="w-4 h-4" />
                  </a>
                )}
              </div>
            ))}
          </div>
        </CollapsibleSection>
      )}
    </div>
  )
}

// Exports Tab Component
function ExportsTab({ meeting, onGeneratePowerPoint, onGeneratePodcast, processing, apiStatus }) {
  const [showPodcastOptions, setShowPodcastOptions] = useState(false)

  return (
    <div className="space-y-6">
      {/* PowerPoint Export */}
      <div className="premium-card-static p-6">
        <div className="flex items-center gap-4 mb-5">
          <div className="w-12 h-12 bg-gradient-to-br from-orange-400 to-orange-500 rounded-xl flex items-center justify-center">
            <FileSpreadsheet className="w-6 h-6 text-white" />
          </div>
          <div>
            <h3 className="font-bold text-gray-900">PowerPoint Presentation</h3>
            <p className="text-sm text-gray-500">Generate professional slide decks</p>
          </div>
        </div>

        <div className="grid md:grid-cols-2 gap-4">
          <button
            onClick={() => onGeneratePowerPoint('internal')}
            disabled={processing.powerpoint}
            className="p-5 border-2 border-gray-200 rounded-xl hover:border-dw-teal hover:bg-dw-teal/5 transition-all text-left disabled:opacity-50"
          >
            <h4 className="font-semibold text-gray-900">Internal Version</h4>
            <p className="text-sm text-gray-500 mt-1">Detailed strategy for D&W team and leadership</p>
            {processing.powerpoint && <Loader2 className="w-4 h-4 animate-spin mt-2 text-dw-teal" />}
          </button>

          <button
            onClick={() => onGeneratePowerPoint('external')}
            disabled={processing.powerpoint}
            className="p-5 border-2 border-gray-200 rounded-xl hover:border-dw-teal hover:bg-dw-teal/5 transition-all text-left disabled:opacity-50"
          >
            <h4 className="font-semibold text-gray-900">External Version</h4>
            <p className="text-sm text-gray-500 mt-1">Polished presentation for client/prospects</p>
            {processing.powerpoint && <Loader2 className="w-4 h-4 animate-spin mt-2 text-dw-teal" />}
          </button>
        </div>
      </div>

      {/* Podcast/Audio Summary */}
      <div className="premium-card-static p-6">
        <div className="flex items-center gap-4 mb-5">
          <div className="w-12 h-12 bg-gradient-to-br from-purple-500 to-purple-600 rounded-xl flex items-center justify-center">
            <Headphones className="w-6 h-6 text-white" />
          </div>
          <div>
            <h3 className="font-bold text-gray-900">Audio Summary</h3>
            <p className="text-sm text-gray-500">Generate a podcast-style audio briefing</p>
          </div>
        </div>

        {!apiStatus.elevenlabs ? (
          <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 text-amber-700 text-sm flex items-center gap-3">
            <AlertTriangle className="w-5 h-5 flex-shrink-0" />
            ElevenLabs API key required for audio generation. Add ELEVENLABS_API_KEY to your .env file.
          </div>
        ) : meeting.podcast ? (
          <div className="space-y-4">
            <audio src={meeting.podcast.downloadUrl} controls className="w-full" />
            <p className="text-sm text-gray-500">
              Generated: {new Date(meeting.podcast.generatedAt).toLocaleString()}
            </p>
          </div>
        ) : (
          <div>
            <button
              onClick={() => setShowPodcastOptions(!showPodcastOptions)}
              className="btn-premium bg-purple-600 hover:bg-purple-700 text-white"
            >
              <Headphones className="w-4 h-4" />
              Generate Audio Summary
            </button>

            {showPodcastOptions && (
              <div className="mt-4 grid md:grid-cols-2 gap-4">
                <button
                  onClick={() => onGeneratePodcast('female')}
                  disabled={processing.podcast}
                  className="p-5 border-2 border-gray-200 rounded-xl hover:border-purple-500 hover:bg-purple-50 transition-all text-left disabled:opacity-50"
                >
                  <h4 className="font-semibold text-gray-900">Female Voice</h4>
                  <p className="text-sm text-gray-500 mt-1">Professional female narrator</p>
                  {processing.podcast && <Loader2 className="w-4 h-4 animate-spin mt-2 text-purple-600" />}
                </button>

                <button
                  onClick={() => onGeneratePodcast('male')}
                  disabled={processing.podcast}
                  className="p-5 border-2 border-gray-200 rounded-xl hover:border-purple-500 hover:bg-purple-50 transition-all text-left disabled:opacity-50"
                >
                  <h4 className="font-semibold text-gray-900">Male Voice</h4>
                  <p className="text-sm text-gray-500 mt-1">Professional male narrator</p>
                  {processing.podcast && <Loader2 className="w-4 h-4 animate-spin mt-2 text-purple-600" />}
                </button>
              </div>
            )}
          </div>
        )}
      </div>

      {/* Other Exports */}
      <div className="premium-card-static p-6">
        <h3 className="font-bold text-gray-900 mb-4">Other Export Options</h3>
        <div className="flex flex-wrap gap-3">
          <a
            href={`/api/export/${meeting.id}/pdf`}
            className="btn-premium btn-secondary"
          >
            <Download className="w-4 h-4" />
            Export as PDF
          </a>
          <a
            href={`/api/export/${meeting.id}/text`}
            className="btn-premium btn-secondary"
          >
            <FileText className="w-4 h-4" />
            Export as Text
          </a>
        </div>
      </div>
    </div>
  )
}

// Collapsible Section Component
function CollapsibleSection({ title, icon: Icon, count, expanded, onToggle, children }) {
  return (
    <div className="border border-gray-200 rounded-xl overflow-hidden">
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between p-4 bg-gray-50 hover:bg-gray-100 transition-colors"
      >
        <div className="flex items-center gap-3">
          {Icon && <Icon className="w-5 h-5 text-dw-teal" />}
          <span className="font-semibold text-gray-900">{title}</span>
          {count !== undefined && (
            <span className="px-2.5 py-0.5 bg-dw-teal/10 text-dw-teal text-xs font-semibold rounded-full">
              {count}
            </span>
          )}
        </div>
        {expanded ? (
          <ChevronUp className="w-5 h-5 text-gray-400" />
        ) : (
          <ChevronDown className="w-5 h-5 text-gray-400" />
        )}
      </button>
      {expanded && (
        <div className="p-5 border-t border-gray-100">
          {children}
        </div>
      )}
    </div>
  )
}
